// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: rss.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rss struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastRun       int64                  `protobuf:"varint,1,opt,name=LastRun,proto3" json:"LastRun,omitempty"`
	Feeds         map[string]int64       `protobuf:"bytes,2,rep,name=Feeds,proto3" json:"Feeds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rss) Reset() {
	*x = Rss{}
	mi := &file_rss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rss) ProtoMessage() {}

func (x *Rss) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rss.ProtoReflect.Descriptor instead.
func (*Rss) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{0}
}

func (x *Rss) GetLastRun() int64 {
	if x != nil {
		return x.LastRun
	}
	return 0
}

func (x *Rss) GetFeeds() map[string]int64 {
	if x != nil {
		return x.Feeds
	}
	return nil
}

var File_rss_proto protoreflect.FileDescriptor

const file_rss_proto_rawDesc = "" +
	"\n" +
	"\trss.proto\x12\x03rss\"\x84\x01\n" +
	"\x03Rss\x12\x18\n" +
	"\aLastRun\x18\x01 \x01(\x03R\aLastRun\x12)\n" +
	"\x05Feeds\x18\x02 \x03(\v2\x13.rss.Rss.FeedsEntryR\x05Feeds\x1a8\n" +
	"\n" +
	"FeedsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B\rZ\vinternal/pbb\x06proto3"

var (
	file_rss_proto_rawDescOnce sync.Once
	file_rss_proto_rawDescData []byte
)

func file_rss_proto_rawDescGZIP() []byte {
	file_rss_proto_rawDescOnce.Do(func() {
		file_rss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rss_proto_rawDesc), len(file_rss_proto_rawDesc)))
	})
	return file_rss_proto_rawDescData
}

var file_rss_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rss_proto_goTypes = []any{
	(*Rss)(nil), // 0: rss.Rss
	nil,         // 1: rss.Rss.FeedsEntry
}
var file_rss_proto_depIdxs = []int32{
	1, // 0: rss.Rss.Feeds:type_name -> rss.Rss.FeedsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rss_proto_init() }
func file_rss_proto_init() {
	if File_rss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rss_proto_rawDesc), len(file_rss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rss_proto_goTypes,
		DependencyIndexes: file_rss_proto_depIdxs,
		MessageInfos:      file_rss_proto_msgTypes,
	}.Build()
	File_rss_proto = out.File
	file_rss_proto_goTypes = nil
	file_rss_proto_depIdxs = nil
}
