// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rss/rss.proto

package rss

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Rss struct {
	LastRun              int64            `protobuf:"varint,1,opt,name=LastRun,proto3" json:"LastRun,omitempty"`
	Feeds                map[string]int64 `protobuf:"bytes,2,rep,name=Feeds,proto3" json:"Feeds,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Rss) Reset()         { *m = Rss{} }
func (m *Rss) String() string { return proto.CompactTextString(m) }
func (*Rss) ProtoMessage()    {}
func (*Rss) Descriptor() ([]byte, []int) {
	return fileDescriptor_95cc919bf63ba5ce, []int{0}
}

func (m *Rss) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rss.Unmarshal(m, b)
}
func (m *Rss) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rss.Marshal(b, m, deterministic)
}
func (m *Rss) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rss.Merge(m, src)
}
func (m *Rss) XXX_Size() int {
	return xxx_messageInfo_Rss.Size(m)
}
func (m *Rss) XXX_DiscardUnknown() {
	xxx_messageInfo_Rss.DiscardUnknown(m)
}

var xxx_messageInfo_Rss proto.InternalMessageInfo

func (m *Rss) GetLastRun() int64 {
	if m != nil {
		return m.LastRun
	}
	return 0
}

func (m *Rss) GetFeeds() map[string]int64 {
	if m != nil {
		return m.Feeds
	}
	return nil
}

func init() {
	proto.RegisterType((*Rss)(nil), "Rss")
	proto.RegisterMapType((map[string]int64)(nil), "Rss.FeedsEntry")
}

func init() {
	proto.RegisterFile("rss/rss.proto", fileDescriptor_95cc919bf63ba5ce)
}

var fileDescriptor_95cc919bf63ba5ce = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2a, 0x2e, 0xd6,
	0x2f, 0x2a, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x6a, 0x60, 0xe4, 0x62, 0x0e, 0x2a,
	0x2e, 0x16, 0x92, 0xe0, 0x62, 0xf7, 0x49, 0x2c, 0x2e, 0x09, 0x2a, 0xcd, 0x93, 0x60, 0x54, 0x60,
	0xd4, 0x60, 0x0e, 0x82, 0x71, 0x85, 0x54, 0xb9, 0x58, 0xdd, 0x52, 0x53, 0x53, 0x8a, 0x25, 0x98,
	0x14, 0x98, 0x35, 0xb8, 0x8d, 0xf8, 0xf5, 0x82, 0x8a, 0x8b, 0xf5, 0xc0, 0x22, 0xae, 0x79, 0x25,
	0x45, 0x95, 0x41, 0x10, 0x59, 0x29, 0x0b, 0x2e, 0x2e, 0x84, 0xa0, 0x90, 0x00, 0x17, 0x73, 0x76,
	0x6a, 0x25, 0xd8, 0x28, 0xce, 0x20, 0x10, 0x53, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34,
	0x55, 0x82, 0x09, 0x6c, 0x3c, 0x84, 0x63, 0xc5, 0x64, 0xc1, 0x98, 0xc4, 0x06, 0x76, 0x89, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x27, 0x08, 0x05, 0x9a, 0x00, 0x00, 0x00,
}
