name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: golang:latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build and Test
        run: |
          make lint test
